### 起源
javascript是在浏览器端运行的脚本语言，处理很多页面的交互，所以js是采用单线程模式工作的，因为如果采用多线程，会导致线程同步问题(一个线程修改了dom，另一个线程也修改了，浏览器不能定位使用哪个线程的方法)。单线程语言中，任务是要排队执行的，但是当执行耗时任务的时候，时间过长会导致程序假死。为了解决耗时任务阻塞执行的问题，js将任务执行模式分为了同步模式和异步模式。

### 执行模式
1. 同步模式 Synchronous
- 同步指的不是同时执行，而是排队/连续执行
- 执行过程总会使用调用栈（call stack），调用栈可以理解为js在执行引擎中维护了一个正在执行的工作表，用于记录正在做的一些任务，当工作表中的任务被清空，意味着这一轮的任务结束。
- 缺点：由于是连续执行，不能插入其他任务，所以在执行耗时任务的时候，程序只能进入等待状态，导致程序假死

```javascript
// 0-加载整体代码，在call stack中加入一个匿名的全局调用(anonymous)

// 1-将console.log('global begin')压入call stack
console.log('global begin')
// 2-将console.log('global begin')弹出call stack

function bar () {
  // 6-将console.log('bar task')压入call stack
  console.log('bar task')
  // 7-将console.log('bar task')弹出call stack
}

function foo () {
  // 3-将console.log('foo task') 压入call stack
  console.log('foo task') // 3
  // 4-将console.log('foo task') 弹出call stack
  // 5-将bar()压入call stack
  bar()
  // 8-将bar()弹出call stack
}

// 3-将foo()压入call stack
foo() 
// 9-将foo()弹出call stack

// 10-将console.log('global end') 压入call stack
console.log('global end')
// 11-将console.log('global end') 弹出call stack
```

2. 异步模式 Asynchronous
- 特点：异步模式不会等待这个任务的结束才开始执行下一个任务，而是在耗时任务开启之后就立即往后执行下一个任务，后续逻辑一般会通过回调函数方式定义
- 作用：解决单线程的js语言无法同时处理大量耗时任务的问题
- 难点：代码执行顺序混乱，不通俗易懂

```javascript
// 0-加载整体代码，在call stack中加入一个匿名的全局调用(anonymous)

// 1-call stack压入console
console.log('global begin')
// 2-call stack弹出console

// 3-call stack压入setTimeout(timer1)
// 4-web API开启1.8s timer1的倒计时器(单独工作，不受线程影响)
setTimeout(
  // 20-将队列第二个事件timer1 压入调用栈call stack
  function timer1 () {
    // 21-压入
    console.log('timer1 invoke')
    // 22-弹出
  }, 1800)
// 5-call stack弹出setTimeout(timer1)

// 6-call stack压入setTimeout(timer2)
// 7-web API开启1s timer2的倒计时器(单独工作，不受线程影响)
setTimeout(
  // 13-Event loop监听到队列变化，将队列第一个事件timer2 压入调用栈call stack
  function timer2 () {
    // 14-压入
    console.log('timer2 invoke')
    // 15-弹出

    // 16-压入setTimeout(inner)
    // 17-计时
    setTimeout(
      // 23-inner倒计时结束, 加入任务队列queue
      // 24-Event loop监听到队列变化将队列第一个事件inner压入调用栈call stack
      function inner () {
        // 25-压入
        console.log('inner invoke')
        // 26-弹出
      }, // 27-弹出inner事件
    1000)
    // 18-弹出setTimeout(inner)
  }, // 19-弹出timer2
1000)
// 8-call stack弹出setTimeout(timer2)

// 9-call stack压入console
console.log('global end')
// 10-call stack弹出console

// 11-timer2倒计时结束，任务队列queue中加入timer2
// 12-timer1倒计时结束，任务队列queue中加入timer1

```

### 事件循环与消息队列
Javascript是单线程的，执行任务的时候需要排队，所以形成了‘任务队列’，"任务队列"是一个事件的队列（也可以理解成消息的队列），IO设备完成一项任务，就在"任务队列"中添加一个事件，表示相关的异步任务可以进入"执行栈"了。主线程读取"任务队列"，就是读取里面有哪些事件。因为读取事件的这个过程是循环不断的，所以整个的这种运行机制又称为Event Loop（事件循环）。

作用：监听调用栈和任务队列，从任务队列中取任务，交给调用栈执行

![](https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/a6f16765d5f04e11acec5cb5eda80a34~tplv-k3u1fbpfcp-zoom-1.image)

- JavaScript是单线程的，但是浏览器不是单线程的，或者说js调用的某些浏览器内部API不是单线程的，例如setTimeOut计时器
- 所谓单线程，指的是代码执行的线程是一个单线程
- 所谓执行模式，指的是运行环境提供的API是以同步或异步模式的方式工作

### 回调函数
- 场景：当异步任务的调用者，想要做的任务不确定何时完成时，将步骤写入函数中，交给异步任务执行者去执行，这个写好步骤的函数称之为回调函数
- 概念：由调用者定义，交给执行者执行的函数，叫回调函数
```javascript
function foo (callback) {
  setTimeout(function () {
    callback()
  }, 3000)
}

foo(function () {
  console.log('这就是一个回调函数')
  console.log('调用者定义这个函数，执行者执行这个函数')
  console.log('其实就是调用者告诉执行者异步任务结束后应该做什么')
})
```

- 直接使用传统回调方式去完成复杂的异步流程，就会导致函数的多层嵌套（回调地狱）
```javascript
$.get('/url1', function (data1) {
  $.get('/url2', data1, function (data2) {
    $.get('/url3', data2, function (data3) {
      $.get('/url4', data3, function (data4) {
        $.get('/url5', data4, function (data5) {
          $.get('/url6', data5, function (data6) {
            $.get('/url7', data6, function (data7) {
              // 略微夸张了一点点
            })
          })
        })
      })
    })
  })
})
```

### Promise异步方案

任务执行过程中有很多耗时任务，比如Ajax操作从网络读取数据，不得不等着结果出来，再往下执行。所以JavaScript语言的设计者将任务分成了两种，一种是同步任务（synchronous），另一种是异步任务（asynchronous）。同步任务指的是，在主线程上排队执行的任务，只有前一个任务执行完毕，才能执行后一个任务；异步任务指的是，不进入主线程、而进入"任务队列"（task queue）的任务，只有"任务队列"通知主线程，某个异步任务可以执行了，该任务才会进入主线程执行，其中Promise就是异步任务，在当前任务队列之后立即执行。

- Promise规范是由CommonJs社区提出的，在ES2015中被标准化，成为语言规范，一个全局的类型
- Promise翻译过来是承诺的意思，承诺有三种状态，开始时是待定状态Pending，结束后有成功状态Fulfilled，和失败状态Rejected
- Promise执行结束后，使用者会收到两种回调函数onFulfilled和onRejected
![](https://p9-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/1af9ff9700314a82982853e2cd5d9cc9~tplv-k3u1fbpfcp-zoom-1.image)
- Promise的本质是使用回调函数的方式，定义异步任务结束后所需要执行的任务

1. 基本用法
```javascript
const promise = new Promise(function (resolve, reject) {
  // 这里用于“兑现”承诺

  // resolve(100) // 承诺达成

  reject(new Error('promise rejected')) // 承诺失败
})

promise.then(function (value) { // onFulfilled回调函数
  // 即便没有异步操作，then 方法中传入的回调仍然会被放入队列，等待下一轮执行
  console.log('resolved', value)
}, function (error) { // onRejected回调函数
  console.log('rejected', error)
})

console.log('end')
```

2. 使用Promise方式实现ajax
```javascript
function ajax (url) {
  return new Promise(function (resolve, reject) {
    var xhr = new XMLHttpRequest()
    xhr.responseType = 'json'
    xhr.open('GET', url)
    xhr.onload = function () {
      if (xhr.status === 200) {
        resolve(xhr.response)
      } else {
        reject(new Error(xhr.statusText))
      }
    }
    xhr.send()
  })
}

ajax('api/users.json')
  .then(function (data) {
    console.log(data)
  }, function(error) {
    console.log(error)
  })
```

3. 链式调用
- Promise虽然使用的是回调函数的方式，但是为了避免回调地狱的问题，promise支持链式调用
- Promise的then方法会返回一个全新的Promise对象，形成一个promise链
- 后面的then方法就是为了上一个then返回的promise对象注册回调
- 前面的then方法中回调函数的返回值会作为后面then方法回调的参数
- 如果回调中返回的是Promise,那后面then方法的回调会等待它的结束

```javascript
ajax('/api/users.json')
  .then(function (value) {
    console.log(1111)
    return ajax('/api/urls.json')
  }) // => Promise
  .then(function (value) {
    console.log(2222)
    console.log(value)
    return ajax('/api/urls.json')
  }) // => Promise
  .then(function (value) {
    console.log(3333)
    return ajax('/api/urls.json')
  }) // => Promise
  .then(function (value) {
    console.log(4444)
    return 'foo'
  }) // => Promise
  .then(function (value) {
    console.log(5555)
    console.log(value)
  })
```

4. 异常处理
- then回调函数支持两个参数，第二个参数会失败状态的回调，此处也可以用catch方法来链式调用

```javascript
// 使用 catch 注册失败回调是更常见的
ajax('/api/users11.json')
  .then(function onFulfilled (value) {
    console.log('onFulfilled', value)
  })
  .catch(function onRejected (error) {
    console.log('onRejected', error)
  })

// then(onRejected) 实际上就相当于 then(undefined, onRejected)
ajax('/api/users11.json')
  .then(function onFulfilled (value) {
    console.log('onFulfilled', value)
  })
  .then(undefined, function onRejected (error) {
    console.log('onRejected', error)
  })
```

- catch和onRejected方法的区别是，catch是给上一个then返回的promise对象指定回调，而不是第一个promise对象指定
- 注册的 onRejected 只是给当前 Promise 对象注册的失败回调，它只能捕获到当前 Promise 对象的异常
- 因为 Promise 链条上的任何一个异常都会被一直向后传递，直至被捕获
- 分开注册的 onRejected， 也就是catch方法相当于给整个 Promise 链条注册失败回调
```javascript
// onRejected捕获不到返回的异步方法的异常
ajax('/api/users.json')
  .then(function onFulfilled (value) {
    console.log('onFulfilled', value)
    return ajax('/error-url')
  }, function onRejected (error) {
    console.log('onRejected', error)
  })

// catch可以捕获返回的异步方法的异常
ajax('/api/users.json')
  .then(function onFulfilled (value) {
    console.log('onFulfilled', value)
    return ajax('/error-url')
  }) // => Promise {}
  .catch(function onRejected (error) {
    console.log('onRejected', error)
  })
```

5. 全局捕获异常
```javascript
// 全局捕获 Promise 异常，类似于 window.onerror
window.addEventListener('unhandledrejection', event => {
  const { reason, promise } = event

  console.log(reason, promise)
  // reason => Promise 失败原因，一般是一个错误对象
  // promise => 出现异常的 Promise 对象

  event.preventDefault()
}, false)

// Node.js 中使用以下方式
process.on('unhandledRejection', (reason, promise) => {
  console.log(reason, promise)
  // reason => Promise 失败原因，一般是一个错误对象
  // promise => 出现异常的 Promise 对象
})
```

6. Promise静态方法
- promise.resolve如果传入的是一个 Promise 对象，Promise.resolve 方法原样返回
```javascript
new Promise(function (resolve, reject) {
  resolve('foo')
})
// 等价于
Promise.resolve('foo')
  .then(function (value) {
    console.log(value)
  })

var promise = ajax('/api/users.json')
var promise2 = Promise.resolve(promise)
console.log(promise === promise2)
```

- promise.resolve如果传入的是带有一个跟 Promise 一样的 then 方法的对象，Promise.resolve 会将这个对象作为 Promise 执行
```javascript
Promise.resolve({
  // 实现了一个thenable的接口
  then: function (onFulfilled, onRejected) {
    onFulfilled('foo')
  }
})
.then(function (value) {
  console.log(value)
})
```
- Promise.reject 传入任何值，都会作为这个 Promise 失败的理由
```javascript
Promise.reject(new Error('rejected'))
  .catch(function (error) {
    console.log(error)
  })

Promise.reject('anything')
  .catch(function (error) {
    console.log(error)
  })
```

7. 并行处理Promise.all
```javascript
// 串行结合并行一起使用
ajax('/api/urls.json')
  .then(value => {
    const urls = Object.values(value)
    const tasks = urls.map(url => ajax(url))
    return Promise.all(tasks)
  })
  .then(values => {
    console.log(values)
  })
```

8. Promise.race 实现超时控制
- Promise.all()是等待所有的任务结束之后才结束
- Promise.race()只会等待第一个结束的任务
```javascript
// 实现ajax请求超时限制功能
const request = ajax('/api/posts.json')
const timeout = new Promise((resolve, reject) => {
  setTimeout(() => reject(new Error('timeout')), 500)
})

Promise.race([
  request,
  timeout
])
.then(value => {
  console.log(value)
})
.catch(error => {
  console.log(error)
})
```
### 宏任务/微任务队列
1. 宏任务：js回调队列中等待的任务，执行过程中增加的额外任务可以作为新的宏任务进到队列排队
2. 微任务：直接在当前任务结束过后立即执行，promise的回调会作为微任务执行
3. 微任务的作用是为了提高整体的响应能力
4. 目前绝大多数异步调用的API都是作为宏任务执行
5. Promise & MutationObserver & process.nextTick 会作为微任务执行

```javascript
// 微任务
console.log('global start')

// setTimeout 的回调是 宏任务，进入回调队列排队
setTimeout(() => {
  console.log('setTimeout')
}, 0)

// Promise 的回调是 微任务，本轮调用末尾直接执行
Promise.resolve()
  .then(() => {
    console.log('promise')
  })
  .then(() => {
    console.log('promise 2')
  })
  .then(() => {
    console.log('promise 3')
  })

console.log('global end')
```

### Generator异步方案（ES2015）、Async/Await语法糖（）
1. generator异步方案：让异步调用再次回归扁平化
```javascript
// 生成器函数回顾
function * foo () {
  console.log('start')

  try {
    const res = yield 'foo'
    console.log(res)
  } catch (e) {
    console.log(e)
  }
}

const generator = foo()

const result = generator.next()
console.log(result)

// generator.next('bar')

generator.throw(new Error('Generator error'))
```

2. generator配合promise的异步方案，模拟请求多个接口
```javascript
function ajax (url) {
  return new Promise((resolve, reject) => {
    var xhr = new XMLHttpRequest()
    xhr.open('GET', url)
    xhr.responseType = 'json'
    xhr.onload = () => {
      if (xhr.status === 200) {
        resolve(xhr.response)
      } else {
        reject(new Error(xhr.statusText))
      }
    }
    xhr.send()
  })
}

function * main () {
  try {
    const users = yield ajax('/api/users.json')
    console.log(users)

    const posts = yield ajax('/api/posts.json')
    console.log(posts)

    const urls = yield ajax('/api/urls11.json')
    console.log(urls)
  } catch (e) {
    console.log(e)
  }
}
```

- generator基础写法
```javascript
const g = main()
const result = g.next()

result.value.then(data => {
  const result2 = g.next(data)
  console.log('result2', result2)

  if (result2.done) return

  result2.value.then(data => {
    const result3 = g.next(data)
    console.log('result3', result3)
    if (result3.done) return

    result3.value.then(data => {
      g.next(data)
    })
  })
})
```
- generator递归写法
```javascript
function co (generator) {
  const g = generator()

  function handleResult (result) {
    if (result.done) return // 生成器函数结束
    result.value.then(data => {
      handleResult(g.next(data))
    }, error => {
      g.throw(error)
    })
  }

  handleResult(g.next())
}

co(main)
// 相关的第三方库：https://github.com/tj/co
```
- Async/Await语法糖：语言层面的异步编程标准
- async写法
```javascript
async function main () {
  try {
    const users = await ajax('/api/users.json')
    console.log(users)

    const posts = await ajax('/api/posts.json')
    console.log(posts)

    const urls = await ajax('/api/urls.json')
    console.log(urls)
  } catch (e) {
    console.log(e)
  }
}

const promise = main()

promise.then(() => {
  console.log('all completed')
})
```
### 模拟Promise源码
一、基本使用
1. Promise是一个类，在执行类的时候传递一个回调函数（执行器）进去，并且执行器会立即实行，执行器接受两个参数(resolve,reject)
2. Promise有三种状态，分别为成功 fulfilled  失败 rejected  等待 pending,一旦状态确定，就不可更改
- pending ---> rejected
- pending ---> fulfilled
3. resolve和reject函数是用来更改状态的
- resolve将状态更改为fulfilled
- reject将状态更改为rejected
4. then方法判断状态返回结果, then方法是被定义在原型对象中的
- 如果状态是成功,调用成功的回调函数, 成功回调有一个参数表示成功之后的值
- 如果状态是失败,调用失败回调函数, 失败回调有一个参数表示失败后的原因
5. 如果成功或者失败回调在异步方法中，需要等待宏任务调用执行，在调用.then方法时，需要将成功失败的函数存储起来
6. 因为同一个promise对象下面的then方法是可以被调用多次的，所以存储成功or失败函数的变量应该是一个数组

```javascript
/*
* 使用promise
* index.js
*/
const promise = new PromiseTest(function (resolve, reject) {
  // reject('失败')
  setTimeout(() => {
    resolve('成功')
  }, 3000)
})

promise.then(value => {
  console.log(value)
}, reason => {
  console.log(reason)
})

/*
* 封装promise
* promiseTest.js
*/
const PENDING = 'pending'
const FULFILLED = 'fulfilled'
const REJECTED = 'rejected'

class PromiseTest {
  constructor (actuator) {
    actuator(this.resolve, this.reject)
  }

  status = PENDING
  value = undefined
  reason = undefined
  successCb = []
  failCb = []

  resolve = value => {
    if (this.status !== PENDING) return
    this.value = value
    this.status = FULFILLED
    // 如果有异步任务，执行已存储的成功函数回调
    while (this.successCb.length) {
      this.successCb.shift()(value)
    }
  }

  reject = reason => {
    if (this.status !== PENDING) return
    this.reason = reason
    this.status = REJECTED
    // 如果有异步任务，执行已存储的失败函数回调
    while (this.failCb.length) {
      this.failCb.shift()(reason)
    }
  }

  then (successCb, failCb) {
    if (this.status === FULFILLED) {
      successCb(this.value)
    } else if (this.status === REJECTED) {
      failCb(this.reason)
    } else {
      // 如果resolve或reject函数异步任务之后执行，先将回调函数存储起来
      this.successCb.push(successCb)
      this.failCb.push(failCb)
    }
  }
}

module.exports = PromiseTest
```

二、链式调用

7. 因为Promise支持链式调用，而then方法是Promise上的实例方法，所以then方法返回的是一个promise对象
8. 因为上一个then方法返回的结果会传递给下一个then方法，所以then方法promise对象也会执行resolve逻辑
9. then方法返回的结果有可能是普通值，也可能是一个promise对象

```javascript
/*
* 使用promise
* index.js
*/
const promise = new PromiseTest((resolve, reject) => {
  // reject('失败')
  setTimeout(() => {
    resolve('成功')
  }, 3000)
})

function other () {
  return new PromiseTest((resolve, reject) => {
    resolve('other')
  })
}

promise.then(value => {
  console.log(value)
})

/*
* 封装promise
* promiseTest.js
*/
const PENDING = 'pending'
const FULFILLED = 'fulfilled'
const REJECTED = 'rejected'

class PromiseTest {
  constructor (actuator) {
    actuator(this.resolve, this.reject)
  }

  status = PENDING
  value = undefined
  reason = undefined
  successCb = []
  failCb = []

  resolve = value => {
    if (this.status !== PENDING) return
    this.value = value
    this.status = FULFILLED
    // 如果有异步任务，执行已存储的成功函数回调
    while (this.successCb.length) {
      this.successCb.shift()(value)
    }
  }

  reject = reason => {
    if (this.status !== PENDING) return
    this.reason = reason
    this.status = REJECTED
    // 如果有异步任务，执行已存储的失败函数回调
    while (this.failCb.length) {
      this.failCb.shift()(reason)
    }
  }

  then (successCb, failCb) {
    let promise2 = new PromiseTest((resolve, reject) => {
      if (this.status === FULFILLED) {
        let res = successCb(this.value)
        // 判断返回值是不是一个promise对象
        if (res instanceof PromiseTest) {
          res.then(resolve, reject)
        } else {
          resolve(res)
        }
      } else if (this.status === REJECTED) {
        failCb(this.reason)
      } else {
        // 如果resolve或reject函数异步任务之后执行，先将回调函数存储起来
        this.successCb.push(successCb)
        this.failCb.push(failCb)
      }
    })
    return promise2
  }
}

module.exports = PromiseTest
```

三、异常处理
1. Promise不允许promise对象循环调用
2. 其它错误：执行器错误，then中发生错误，异步任务执行后错误
3. then方法的参数可以选填，不填时返回值自动传入下一个then方法中

```javascript
// 执行中的错误
const promise = new PromiseTest(function (resolve, reject) {
  throw Error('executor error')
  resolve('成功')
})

promise.then(value => {
  console.log(value)
}, reason => {
  console.log(reason.message)
})

// then中发生错误
const promise = new PromiseTest(function (resolve, reject) {
  // throw Error('executor error')
  resolve('成功')
})

promise.then(value => {
  console.log(value)
  throw Error('then error')
}, reason => {
  console.log('then1', reason.message)
}).then(value => {
  console.log(value)
}, reason => {
  console.log('then2', reason.message)
})

// then方法中不传参数
const promise = new PromiseTest(function (resolve, reject) {
  resolve('成功')
})

promise.then().then().then(value => {
  console.log(value)
})

/*
* 封装promise
* promiseTest.js
*/
const PENDING = 'pending'
const FULFILLED = 'fulfilled'
const REJECTED = 'rejected'

class PromiseTest {
  constructor (executor) {
    try {
      executor(this.resolve, this.reject)
    } catch (e) {
      this.reject(e)
    }
  }

  status = PENDING
  value = undefined
  reason = undefined
  successCb = []
  failCb = []

  resolve = value => {
    if (this.status !== PENDING) return
    this.status = FULFILLED
    this.value = value
    // 如果有异步任务，执行已存储的成功函数回调
    while (this.successCb.length) {
      this.successCb.shift()()
    }
  }

  reject = reason => {
    if (this.status !== PENDING) return
    this.status = REJECTED
    this.reason = reason
    // 如果有异步任务，执行已存储的失败函数回调
    while (this.failCb.length) {
      this.failCb.shift()()
    }
  }

  then (successCb, failCb) {
    // 实现then方法参数可选
    successCb = successCb ? successCb : value => value
    failCb = failCb ? failCb : reason => { throw reason }

    let promise2 = new PromiseTest((resolve, reject) => {
      if (this.status === FULFILLED) {
        // promise2在微任务队列中取不到，所以要在宏任务后获取
        setTimeout(() => {
          try {
            let res = successCb(this.value)
            // 判断 x 的值是普通值还是promise对象
            // 如果是普通值 直接调用resolve
            // 如果是promise对象 查看promsie对象返回的结果
            // 再根据promise对象返回的结果 决定调用resolve 还是调用reject
            resolvePromise (promise2, res, resolve, reject)
          } catch (e) {
            reject(e)
          }
        }, 0)
      } else if (this.status === REJECTED) {
        setTimeout(() => {
          try {
            let res = failCb(this.reason)
            resolvePromise (promise2, res, resolve, reject)
          } catch (e) {
            reject(e)
          }
        }, 0)
      } else {
        // 如果resolve或reject函数异步任务之后执行，先将回调函数存储起来
        this.successCb.push(() => {
          setTimeout(() => {
            try {
              let res = successCb(this.value)
              resolvePromise (promise2, res, resolve, reject)
            } catch (e) {
              reject(e)
            }
          }, 0)
        })
        this.failCb.push(() => {
          setTimeout(() => {
            try {
              let res = failCb(this.reason)
              resolvePromise (promise2, res, resolve, reject)
            } catch (e) {
              reject(e)
            }
          }, 0)
        })
      }
    })
    return promise2
  }
}

function resolvePromise (promise2, res, resolve, reject) {
  if (promise2 === res) {
    // promise不能重复调用
    return reject(new TypeError('Chaining cycle detected for promise #<Promise>'))
  }
  if (res instanceof PromiseTest) {
    res.then(resolve, reject)
  } else {
    resolve(res)
  }
}

module.exports = PromiseTest
```

四、静态方法
1. 实现异步并发：Promise.all
- 入参是一个数组，数组的各项可以是一个promise，也可以是一个普通值
- 返回的是一个promise对象，promise对象.then方法回调的结果也是一个数组，并且按照入参顺序执行
- 如果入参是一个promise对象，那么执行.then方法后返回结果，如果入参是一个普通值，直接返回
- 如果入参的promise对象里面有一个异步任务，那么等待异步任务执行过后再返回，即入参的数量和结果的数量相等后再正确返回
- 如果在执行过程中有一个promise异常，那么直接将整个promise改为失败状态
2. 实现Promise.resolve
- 如果传入普通值，创建一个promise对象，将值传入后返回
- 如果传入promise对象，直接返回

```javascript
/**
 * 使用promise并发处理
 * index.js
 * */
function p1 () {
  return new PromiseTest(function (resolve, reject) {
    setTimeout(function () {
      resolve('p1')
    }, 2000)
  })
}

function p2 () {
  return new PromiseTest(function (resolve, reject) {
    resolve('p2')
  })
}

// 并发处理
PromiseTest.all(['a', 'b', p1(), p2(), 'c']).then(res => {
  console.log(res)
})

// resolve方法
PromiseTest.resolve(p2()).then(value => console.log(value))

/**
 * 封装promise，部分代码
 * promiseTest.js
 * */
class PromiseTest {
  .......
  static all (array) {
    let result = []
    let index = 0 // 用于标记所有任务是否执行完毕
    return new PromiseTest((resolve, reject) => {
      function addData(key, value) {
        result[key] = value
        index ++
        if (index === array.length) {
          resolve(result)
        }
      }
      for (let i = 0; i < array.length; i++) {
        let current = array[i]
        if (current instanceof PromiseTest) {
          current.then(value => {
            addData(i, value)
          }, reason => {
            reject(reason)
          })
        } else {
          addData(i, array[i])
        }
      }
    })
  }

  static resolve (value) {
    if (value instanceof PromiseTest) {
      return value
    }
    return new PromiseTest(resolve => resolve(value))
  }
  ......
}
```

五、其它实例方法
1. 实现finally方法
- 无论成功还是失败都会被执行一次
- 方法后面可以链式调用then方法返回最终结果
- 如何finally方法返回的是一个promise，会等待promise执行之后再执行下一个then方法
2. 实现catch方法：用来处理当前promise对象最后为失败状态的情况的

```javascript
/**
 * 使用promise
 * index.js
 * */
function p1 () {
  return new PromiseTest(function (resolve, reject) {
    setTimeout(function () {
      resolve('p1')
    }, 2000)
  })
}

function p2 () {
  return new PromiseTest(function (resolve, reject) {
    reject('p2 reject')
    // resolve('p2 resolve')
  })
}

p2().finally(() => {
  console.log('finally')
  return p1()
}).then(value => console.log(value))
  .catch(reason => console.log(reason))

/**
 * 封装promise，部分代码
 * promiseTest.js
 * */
class PromiseTest {
  .......
  finally (callback) {
    return this.then(value => {
      return PromiseTest.resolve(callback()).then(() => value)
    }, reason => {
      return PromiseTest.resolve(callback()).then(() => { throw reason })
    })
  }

  catch (failcallback) {
    return this.then(undefined, failcallback)
  }
  .......
}
```